### PR TITLE
Feature placeholder attribute for filter

### PR DESCRIPTION
**Pull request by cboelter**
This PullRequest adds the possiblilty to use the placeholder attribute for both the search widget and the free input range widget. The implementation is similar to the attribute_text. I've checked the changes with the build.xml and the included phpcq-tasks.
Please check the PullRequest and send me feedback if any changes are required.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [x] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by cboelter** [comment]
Is there any feedback for my PullRequest?

**Comment by zonky2** [comment]
@cboelter sorry, we work hard at MM 2.1 - I hope, I can check your PR at next days... versprochen!

**Comment by zonky2** [comment]
> The implementation is similar to the attribute_text.

... you mean filter_text? https://github.com/MetaModels/filter_text/pull/24/files

works fine

shot383

**Comment by cboelter** [comment]
@zonky2 you are right, I mean the filter_text :)

**Comment by cboelter** [comment]
@zonky2 any news on this topic?

**Comment by zonky2** [comment]
leider nein :-(

hier kann nur @stefanheimes die Sachen mergen und taggen - geprüft/getestet habe ich soweit alles...

**Pull request merged**
